### PR TITLE
hotfix for compilation errors in knxd on Buster #651

### PR DESCRIPTION
**Pull request by holgerfriedrich**
Decided to lift libfmt to from 3.0.0 to 5.0.0. Compiles and installs.
Not tested on my system, knxd not in use.

Signed-off-by: Holger Friedrich <mail@holger-friedrich.de>

### CODE REVIEW

**Comment by mstormi** [comment]
why would you want to compile on your box ? Can't expect that to work IMHO.
knxd can be installed from the menu so there's not even a need for that.

**Comment by holgerfriedrich** [comment]
@mstormi Compilation is actually triggered by installation via menu.
Not sure if the way of providing it is the best. There are two other open issues on knxd, #85 and #321. I think #321 discusses a different option of installing it.

My focus right now is just to make as many of the menu options work on the new 1.5 image / Buster.
I cannot test it anyways, not using knxd.

**Comment by holgerfriedrich** [comment]
@EliasGabrielsson please merge the hotfix.

Good to have it available for Buster as a package. This will make it easier to keep it up to date and the system clean. Our overall approach should be to use as much packages as possible.

Though, unless we do not remove support for Ubuntu, Jessie, and Stretch it will complicate things.

**Comment by EliasGabrielsson** [comment]
There is a planned clean up for at least Ubuntu and Jessie coming up this fall I guess.
Let's look into it when it happen. Just of curiosity do you use KNX system yourself?

**Comment by holgerfriedrich** [comment]
> There is a planned clean up for at least Ubuntu and Jessie coming up this fall I guess.
> Let's look into it when it happen.
Agreed. I can support work for Debian/Raspbian based distros.

> Just of curiosity do you use KNX system yourself?
Yes, but not knxd. OH knx binding via IP interface.

**Comment by mstormi** [comment]
does it work?
Please shellsheck all work from now on

 functions/packages.bash line 325:

  cond_redirect sed -i 's#cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX fmt/#cmake -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX .#' /tmp/install_knxd_systemd.sh || FAILED=1

                       ^-- SC2016: Expressions don't expand in single quotes, use double quotes for that.

**Comment by holgerfriedrich** [comment]
@mstormi this is intended and works.
Is it the correct approach to add `# shellcheck disable=SC2016` before this line?
